### ISSUE TITLE
Make availability of refactorings less "picky" about what's selected

### ISSUE THREAD

**Issue by randycoulman** [gp-pereira/refactorex#15]
Thanks so much for this long-awaited tool! I'm going to open a few issues based on my early usage of RefactorEx, but please know that I'm extremely grateful for all of your work on this so far!

As I've started using RefactorEx, I'm finding that the refactorings I want to use are not always available. The sense I'm getting is that perhaps there are more AST patterns that need to be recognized in order to make the refactorings available.

Here are a few examples of what I mean, all taken from [this file from one of my open-source projects](https://github.com/randycoulman/mix_test_interactive/blob/main/lib/mix_test_interactive.ex). Note that this is not an exhaustive list, but only a sampling of some things I've found:

- On line 21, if I place my cursor somewhere in `@application`, the only available refactoring is `Introduce Pipe`. I'd expect to see some `Inline Constant`, or Extract options available too.
- On that same line, if I highlight the entire word `application` (not including the `@`), I am given the option to `Extract Variable`, which is incorrect in this context. I am able to perform a rename
- On that same line, if I highlight the entire `@application` string, I am now given the option to `Inline Constant` as I expect. If I hit `F2` to rename the constant, I'm told that the element cannot be renamed. The same is true if I highlight the entire constant at its definition point on line 10.
- If I highlight the word `formatted` on line 43 (or place my cursor inside of the word), I am able to rename as expected. However, if I highlight the usage of that variable on line 44, I am not able to rename it. I'd love to be able to rename things from any usage of them, not just the definition.

**Comment by gp-pereira** [comment]
Hi there, 

1. Inline Constant and extract options only work on selections, that's way you are not seeing them by only placing the cursor, I don't intend to modify this behaviour now at least. 
2. Can reproduce, definitely a bug.
3. Can reproduce, definitely a bug.
4. Fixed. RefactorEx now accepts usages for renaming. 
5. Selecting all anonymous functions (from `fn` until `end`)  yield some refactorings like the print below. Collapse anonymous functions require no pattern matching on the function header, just plain args (`fn a, b -> ... end`)
![Image](https://github.com/user-attachments/assets/e6dba566-aa05-4cbe-af2b-7693fc8bc114)
6. Also showed the expected refactorings for me.
![Image](https://github.com/user-attachments/assets/4769277e-18a4-481c-9a8c-0c71d6fc0ba8)
7. Same.
![Image](https://github.com/user-attachments/assets/6a5130b8-922e-455e-8120-267447d47f7b)

I've been fixing minor issues since this was open, maybe that's way it seems to be working now. Can you give it a try on the solved ones? I'll come back close this issue when I fix both reproducable bugs.

**Comment by gp-pereira** [comment]
Hello friend, hope you're well. 

![Image](https://github.com/user-attachments/assets/2d9a19da-3eb2-4c86-abba-b9e5d0bd6905)
![Image](https://github.com/user-attachments/assets/59c59652-0abb-43dd-aed4-8f77d81f9ab1)

In both cases, I was able to perform the rename. The exception you are seeing is from the rename_function refactoring which is crashing for some reason I didn't investigate yet, but all of them run on separate Tasks, so even if it crashes, it won't interrupt other functionality. 

I'm really not sure why you are seeing a different behavior than me tho. Which version of Elixir are you using?

**Comment by randycoulman** [comment]
I'm using the following (from my `.tool-versions` file):
```
erlang 27.2
elixir 1.18.1-otp-27
```

**Comment by gp-pereira** [comment]
Hmmm yeah, I think I found the problem. From elixir v1.17 and forward, the produced AST is slightly different from olders versions. I've been building and testing it on v1.13. I'll have to adjust those parts to support the newer versions. Could you confirm that it works for you in an older elixir version pls? >1.16. In the mean time, I hope to figure out a way to make both ASTs compatible.

**Comment by gp-pereira** [comment]
On v1.17, I am able to reproduce most problems you described, which is great!

**Comment by gp-pereira** [comment]
Hey, I've just pushed some adjustments on code reading and parsing that should solve #5 and the renaming for you. Give it a try whenever you can pls. I'll tackle the other bugs tomorrow hopefully.

**Comment by randycoulman** [comment]
Hey, @gp-pereira! I just tested the new version and it definitely seems better. #5 appears to be fixed as does #6. #7 works on the call site, but not the definition site (if it's even supposed to work there).

Renaming is somewhat better, but still some weird edge cases.

I also tried an older version of Elixir/Erlang (1.15 and 1.16 with OTP 26). There was no significant difference in the bug cases that I could see (this was prior to upgrading to the latest version of the extension).

Thanks for working on these issues!

**Comment by gp-pereira** [comment]
Hi @randycoulman 

Oh yeah you currently cannot inline all usages from the definition. I think we can make this work in the future tho. I still not sure how I feel about not deleting the function after inline the only usage as well, but detecting that can be quite tricky. 

I see. Can you send me the edge cases on rename? Also, if you want, I can guide you around the repo, so you can become a contributor too. All your reports are helping dramastically the evolution of this tool and I'm really glad for them.

In the mean time, I will move to #2 and #3.

**Comment by gp-pereira** [comment]
Hello again, 

I think I've solved #2 by ignoring parts of constants on extract variable and introduce io inspect and #3 by improving the conversion from a cursor position to what should be selected. I made sure that you can rename from the beggining, the middle, the end, selecting from begin to end and vice-versa and only selecting/pointing inside the constant and other structures.

Both fixes are out on v0.1.34 and all issues raised here are done I guess. I'll again for you so we can close this one!

Thank you for taking the time to reporting these.

**Comment by randycoulman** [comment]
I just tested the latest version. Here are my results so far:
- 1 - still not working, but you said earlier that's expected, so ✅ 
- 2 - working ✅ 
- 3 - working ✅ 
- 4 - working ✅ 
- 5 - working ✅ 
- 6 - working ✅ 
- 7 - working at call site if I select the entire function call including arguments; not working at the definition site, but you explained that above, so ✅ 
  - should it be possible to inline a function by having the cursor inside the function name (or with the entire function name selected)? Or only when the entire call is selected?
- The later-reported problem with the `args` variable is now fixed; it still produces the unhandled exception, though - ✅ 
- I am no longer seeing weird edge cases when renaming - ✅ 

Based on this, I'll go ahead and close the issue. Thanks so much!

**Comment by randycoulman** [comment]
> Also, if you want, I can guide you around the repo, so you can become a contributor too. All your reports are helping dramastically the evolution of this tool and I'm really glad for them.

Thanks for the offer! Let me think about it and decide if I have the bandwidth to take this on. I feel like I'd need to learn a lot more about manipulating the AST and such to be of much help.

I'll definitely file more issues as I run into problems. I really want this tool to exist and work well and I can't thank you enough for creating it!

**Comment by gp-pereira** [comment]
Hi,

> * should it be possible to inline a function by having the cursor inside the function name (or with the entire function name selected)? Or only when the entire call is selected?
I think that would go against the established patterns for the tool, but we can definitely revisit it later.

> Thanks for the offer! Let me think about it and decide if I have the bandwidth to take this on. I feel like I'd need to learn a lot more about manipulating the AST and such to be of much help.
That's great! I'll be waiting to hear from you. The Elixir AST is quite nice to work with, specially with Sourceror. I'm quite proud of the test framework I've built as well. Take a look whenever you have some time. 

> I'll definitely file more issues as I run into problems.
Please, I can't thank you enough for that!
